### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by giovp** [giovp/spatialdata-sandbox#1]
### Available datasets
- [x] **merfish**
- [x] **mibitof**
- [x] **nanostring**
- [x] **toy/artificial dataset**
- [x] **visium** 

### Missign datasets
- [ ] maldi (from metaspace, see link in the comments)
- [ ] nanostring (GeoMX DSP, see link in the coments)
- [ ] vizgen merfish (any of these https://vizgen.com/data-release-program/)
- [ ] multimodal multi-fov dataset from the paper [Spatially resolved clonal copy number alterations in benign and malignant tissue](https://www.nature.com/articles/s41586-022-05023-2)
- [ ] codex/ t-CyCIF (see link in the comments)
- [ ] 3D single molecule dataset with time and multiple samples (described in the comments)
- [ ] 3D multi-fov high content hiPSCs https://zenodo.org/record/7120354#.YzRXy-xBxzU
- [ ] 2 datasets from Molecular Cartography from Resolve Biosciences, described in the comments
- [ ] stereoseq data https://www.sciencedirect.com/science/article/pii/S0092867422003993?via%3Dihub
- [ ] lightset data (link in the comments and [zulip discussion](https://scverse.zulipchat.com/#narrow/stream/315824-spatial/topic/lightseq))
- [ ] slideseq + tcr-seq [zulip discussion](https://scverse.zulipchat.com/#narrow/stream/315824-spatial/topic/slideseq.2Btcr-seq)
- [x] xenium (implement reader in spatialdata-io and add a dataset from 10x)
- [ ] EEL FISH
- [ ] BaSISS, breast cancer (see commonts)
- [ ] upcoming BICCN Zhuang lab data or Allen Institute MERSCOPE data (suggestion from Brian Long)
- [ ] [in-situ sequencing dataset](https://colab.research.google.com/github/NBISweden/workshop-spatial/blob/main/labs/00_precourse.ipynb#scrollTo=ehXljD0Wq2Sy) and [other notebooks with analysis from a course from NBISweden](https://github.com/NBISweden/workshop-spatial/tree/main/labs)

**Comment by melonora** [comment]
Looks like there is a CODEX dataset we can get without having to wait on a rep: https://portal.hubmapconsortium.org/browse/dataset/053544cd63125fc25f6a71a8f444bafc#files

**Comment by giovp** [comment]
@LucaMarconato could you post the link to the metaspace and the nanostring geomx that you had in mind?

**Comment by LucaMarconato** [comment]
- For the Nanostring I would go for this one (there are richer ones but are not public, so I would start with this): https://devpost-public.s3.amazonaws.com/NanoString/NanoString%20Dataset%20README.pdf
- For MALDI we can use this one, that combines both raster expression and a background raster image, also the raster expression is "masked" (not a rectangular crop), so it's a good example for us: https://metaspace2020.eu/annotations?db_id=26&ds=2019-03-28_09h18m57s&q=mouse%20brain

**Comment by LucaMarconato** [comment]
Here is a cool 3D single-molecule dataset with time information and multiple samples (multiple coordinate spaces) and paired with images. It would benefit from our infrastructure for deep learning applications. It's some GB so we need to subsample. 
The single-molecule data can be downloaded from [here](https://oc.embl.de/index.php/s/sszVT1ZAUB2LOFW) (link found [in this paper](https://www.biorxiv.org/content/10.1101/2021.10.12.463947v3.full)). The associated images are not public (will be soon), but for the moment we will have access privately.

**Comment by LucaMarconato** [comment]
2 datasets from Resolve:
Mouse skin (melanoma) -  from this publication: https://www.nature.com/articles/s41586-022-05242-7
Data available here: https://zenodo.org/record/6856193#.Yzr3H3ZByF5
 
Mouse and human liver – from this publication: https://www.cell.com/cell/fulltext/S0092-8674(21)01481-1?
Data available here: https://cloud.irc.ugent.be/public/index.php/s/HrXG9WKqjqHBEzS

**Comment by kevinyamauchi** [comment]
Serial sections with different immunofluorescence techniques applied: https://mcmicro.org/datasets/#whole-slide-images-wsis

I haven't opened it, but based on the description I think it also comes with registration transformations, segmentation masks and measurements. Might be a nice example.

https://mcmicro.org/datasets/#whole-slide-images-wsis

**Comment by kevinyamauchi** [comment]
Lightseq - sequencing + imaging

https://www.nature.com/articles/s41592-022-01604-1#data-availability

**Comment by ivirshup** [comment]
@kevinyamauchi, more resources (including notebooks for handling raw data) from their website: [lightseq.io](https://www.lightseq.io)

**Comment by giovp** [comment]
- [ ] nanostring cosmx NSCLC
- [ ] Xenium 10x genomics
- [ ] Vizgen MERSCOPE
- [ ] Visium + CNV Lundeberg lab
- [ ] MALDI from Bishoy
- [ ] One CODEX, or IMC, or MIBITOF, CyCIF

**Comment by LucaMarconato** [comment]
Nice dataset and study from our colleagues at EBI and DKFZ: [base-specific in situ sequencing (BaSISS), for studying clonal evolution in breast cancer](https://www.nature.com/articles/s41586-022-05425-2)

**Comment by berl** [comment]
hey all- I'm excited to learn about this `SpatialData` project and see the progress!

It looks like the `readme.MD` refers to the MERSCOPE data as being from the Zhuang lab, but the download code [here](https://github.com/giovp/spatialdata-sandbox/blob/0a3f7e6b402582634fcf250d72d0ec2085047364/merfish/download.py) shows it grabbing the VISp data from our prototype MERFISH pipeline.  It's fine to use this if you want, but

1.  it's a bit of an orphan dataset in terms of formatting, technical details, etc. upcoming BICCN Zhuang lab data or Allen Institute MERSCOPE data will be more useful long term.
2. If you continue to use it, please change the readme.md to reflect that this is data from the Allen Institute prototype MERFISH pipeline.

**Comment by LucaMarconato** [comment]
Thank you @berl we are working for making a beta release the soonest!

I have updated the README.md with the correct data attribution, sorry for that. And thank you for pointing us to the datasets you mentioned.

**Comment by kevinyamauchi** [comment]
Thanks for catching the misattribution, @berl . Sorry about that!

> it's a bit of an orphan dataset in terms of formatting, technical details, etc. upcoming BICCN Zhuang lab data or Allen Institute MERSCOPE data will be more useful long term.

Do you know when/where those datasets will be released? I'd be interested in checking them out.

**Comment by kevinyamauchi** [comment]
Curio (commercialized slideseq) has example data upon request. It could be worth making a reader if we can get some of the data.

https://curiobioscience.com/example-data/

**Comment by LucaMarconato** [comment]
Closing, enough datasets added.
