### ISSUE TITLE
Merfish Xenium radii fail

### ISSUE THREAD

**Issue by melonora** [giovp/spatialdata-sandbox#36]
When converting to zarr currently these datasets fail because not all radii are above 0. @LucaMarconato

**Comment by LucaMarconato** [comment]
Thanks for reporting. Does this affectr the merfish or the xenium data? In the case of merfish I compute the radius here: https://github.com/giovp/spatialdata-sandbox/blob/ceb8eddc1fdc441b33fcd84d4f3e7c734bf84b92/merfish/download.py#L120.

**Comment by LucaMarconato** [comment]
So are some radii 0? In that case I'd drop the cells inside the `download.py` script.

**Comment by LucaMarconato** [comment]
Fixed with https://github.com/giovp/spatialdata-sandbox/pull/37.
